---

- name: Interface Operations
  hosts: routers
  gather_facts: false
  connection: network_cli


  tasks:
    
    - name: configure interface settings
      cisco.ios.ios_config:
        lines:
        - description test interface
        - ip address 172.31.1.1 255.255.255.0
        parents: interface Ethernet0/1
    - name: configure ip helpers on multiple interfaces
      cisco.ios.ios_config:
        lines:
        - ip helper-address 172.26.1.10
        - ip helper-address 172.26.3.10
        parents: '{{ item }}'
      with_items:
      - interface Ethernet0/2
      - interface Ethernet0/3   
    - name: load new acl into device
      cisco.ios.ios_config:
       lines:
         - 10 permit ip host 192.0.2.1 any log
         - 20 permit ip host 192.0.2.2 any log
         - 30 permit ip host 192.0.2.3 any log
         - 40 permit ip host 192.0.2.4 any log
         - 50 permit ip host 192.0.2.5 any log
        parents: ip access-list extended test
        before: no ip access-list extended test
        match: exact  

    - name: save running to startup when modified
      cisco.ios.ios_config:
        save_when: modified 


