---

- name: Cisco ip interface brief + ip route
  hosts: routers
  gather_facts: false
  connection: network_cli

  tasks:
    - name: run show ip interface brief + ip route
      ios_command:
        commands:
          - show ip interface brief
          - show ip route
      register: output

  tasks:
    - name: save output
      local_action: "copy content='{{ config.stdout[0] }}' dest={{ /root/ansible_eve_ng/ }}{{ inventory_hostname }}.txt"


