---

- name: Cisco ip interface brief + ip route
  hosts: routers
  gather_facts: false
  connection: network_cli

  tasks:
    - name: run show ip interface brief + ip route
      ios_command:
        commands:
          - show ip interface brief
          - show ip route
      register: output

  tasks:
    - name: save output ~/ansible_eve_ng/outputs/
      copy: 
       content: "{{ config.stdout[0] }}"
       dest: "~/ansible_eve_ng/outputs/show_run_{{ inventory_hostname }}.txt"

