---

- name: Cisco Vlan
  hosts: routers
  gather_facts: false
  connection: local

  tasks:

    - name: ensure that the desired snmp strings are present
      cisco.ios.ios_config:
        commands:
          - snmp-server community ansible-public RO
          - snmp-server community ansible-private RW
        provider: 
          username: ansi
          password: 123
          host: "{{ inventory_hostname }}"
