---

- name: Cisco Vlan
  hosts: routers
  gather_facts: false
  connection: network_cli

  tasks:	
    - name: Create vlan
      cisco.ios.ios_vlan:
       config:
        aggregate:
         - vlan_id: 100
           name: test-vlan
       state: present

    - name: Add interfaces to VLAN
      cisco.ios.ios_vlan:
       config:
       - vlan_id: 100
         interfaces:
         - Ethernet0/2
         - Ethernet0/1
