---

- name: Cisco Vlan
  hosts: routers
  gather_facts: false
  connection: network_cli

  tasks:	
    - name: Create vlan
      cisco.ios.ios_vlan:
      vlan_id: 100
      name: test-vlan
      state: present

    - name: Add interfaces to VLAN
      cisco.ios.ios_vlan:
      vlan_id: 100
      interfaces:
      - GigabitEthernet0/0
      - GigabitEthernet0/1
